name: flutter_calendar_view
description: A package that provides a customizable day view calendar widget.
version: 0.0.4
homepage: https://github.com/appnormal/flutter_calendar_view

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
